version: "3"

services:
  app:
    container_name: learn-github-actions-app
    build:
      context: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t /app/public
